[project]
name = "aki"
version = "0.10.7-rc3"
readme = "README.md"
authors = [
    { name = "nroulon", email = "nicolas.roulon@4sh.fr" }
]
requires-python = ">=3.9"
dependencies = [
    "docker ==7.1.0",
    "python-dotenv ==1.1.1",
    "PyYAML ==6.0.2",
]

[dependency-groups]
dev = [
    "pytest ==8.2.0",
    "yapf ==0.40.2",
    "tox ==4.15.0",
    "coverage ==7.5.0"
]

[project.scripts]
aki = "aki.cli:main"

[tool.pytest.ini_options]
addopts = "--ignore sample --ignore tests/resources"


[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
